// UI strings of the 3D Lab. Teaching content is in specimens.js, posters.js
// and quiz.js; this file only holds the words on buttons, panels and hints.

export const UI = {
  tr: {
    title: "Foraminifer Laboratuvarı",
    introLead:
      "Deniz yüzeyinden derin denize uzanan bir yolculuk: 7 gerçek foraminifer taraması, 1 sanat eseri, duvarlarda 5 bilgi panosu ve bir mikroskop. Hepsini incele, sonra kendini sına.",
    introGoals: ["Planktonik ve bentik türleri ayırt et", "Odacık dizilimlerini tanı", "Foraminiferlerin jeologlara ne anlattığını öğren"],
    loading: "Modeller yükleniyor",
    ready: "Modeller hazır",
    startTour: "Rehberli tura başla",
    freeRoam: "Serbest dolaş",
    controlsWalk: "Yürü",
    controlsLook: "Etrafa bak",
    controlsClick: "İncele / oraya git",
    controlsWheel: "İleri / geri",
    controlsTouch: "Dokunmatik: sürükle = bak, dokun = incele / git",
    keyDrag: "Sürükle",
    keyClick: "Tıkla",
    keyWheel: "Tekerlek",
    hint: "Bir sergiye ya da panoya tıkla · zemine tıklayarak oraya yürü",
    clickToInspect: "incelemek için tıkla",
    clickToRead: "okumak için tıkla",
    notebook: "Keşif defteri",
    exhibits: "Sergiler",
    boards: "Panolar",
    studied: "incelendi",
    read: "okundu",
    tour: "Rehberli tur",
    continueTour: "Tura devam et",
    quiz: "Kendini sına",
    bestScore: "En iyi skor",
    close: "Kapat",
    prev: "Önceki",
    next: "Sonraki",
    finishTour: "Tur bitti: kendini sına",
    tabs: { overview: "Genel", identify: "Nasıl tanınır?", why: "Jeolojik önemi", source: "Örnek ve kaynak" },
    life: "Yaşam biçimi",
    wall: "Kavkı duvarı",
    arrangement: "Odacık dizilimi",
    habitat: "Yaşam alanı",
    record: "Fosil kaydı",
    realSize: "Gerçek boyut",
    typicalSize: "Tipik boyut",
    sizeUnknown: "tipik boyut; bu örneğin ölçüsü verilmemiş",
    sizeRuler: "Boyut karşılaştırması",
    terms: "Bu kartta geçen terimler",
    lookFor: "Mikroskopta neye bakmalı?",
    specimenInfo: "Örnek",
    modelCredit: "3D model",
    license: "Lisans",
    modified: "Web için sadeleştirildi (üçgen sayısı azaltıldı, dosya sıkıştırıldı).",
    viewSource: "Orijinal modeli aç",
    artBadge: "Sanat eseri · gerçek örnek değil",
    viewer: {
      mode: "Görünüm",
      solid: "Yüzey",
      xray: "Röntgen",
      section: "Kesit",
      rotate: "Döndür",
      reset: "Sıfırla",
      depth: "Kesit derinliği",
      loadingDetail: "Yüksek çözünürlüklü model yükleniyor…",
      dragHint: "Sürükle: döndür · tekerlek: yakınlaş",
      noInternal: "Bu model yalnızca dış yüzeyi içerir; iç yapı yok.",
      internalHint: "Bu modelde kavkının içindeki odacıklar da var: Röntgen ya da Kesit ile bak.",
      sectionHint: "İnce kesit gibi: ön tarafı kaldırıp odacıkların içine bak.",
    },
    quizTitle: "Kendini sına",
    quizIntro: "8 soru: türleri tanı, yaşam biçimlerini ve dizilimleri hatırla. Her cevaptan sonra açıklamasını göreceksin.",
    quizStart: "Başla",
    question: "Soru",
    correct: "Doğru!",
    wrong: "Yanlış.",
    answerWas: "Doğru cevap",
    seeResult: "Sonucu gör",
    result: "Sonuç",
    retry: "Tekrar dene",
    backToLab: "Laboratuvara dön",
    studyAgain: "Tekrar bakmaya değer",
    resultMessages: ["Başlangıç için iyi — sergileri bir tur daha gez.", "Fena değil! Birkaç sergiye tekrar göz at.", "Çok iyi! Neredeyse bir mikropaleontolog gibisin.", "Kusursuz! Foraminiferler senden sorulur."],
    monitorTitle: "ForamID Tanı Destek Sistemi",
    monitorText:
      "Laboratuvarda gördüğün özellikler (kavkı duvarı, odacık dizilimi…) tanı aracının sorduğu karakterlerin ta kendisi. Gerçek bir ince kesit görüntüsüyle adım adım cins tanısı yapmayı dene.",
    monitorGo: "Tanı aracını aç",
    help: "Yardım",
  },
  en: {
    title: "Foraminifera Laboratory",
    introLead:
      "A journey from the sea surface to the deep sea: 7 real foraminifera scans, 1 artwork, 5 information boards on the walls and a microscope. Study them all, then test yourself.",
    introGoals: ["Tell planktonic from benthic species", "Recognise chamber arrangements", "Learn what foraminifera tell geologists"],
    loading: "Loading models",
    ready: "Models ready",
    startTour: "Start the guided tour",
    freeRoam: "Explore freely",
    controlsWalk: "Walk",
    controlsLook: "Look around",
    controlsClick: "Inspect / go there",
    controlsWheel: "Forward / back",
    controlsTouch: "Touch: drag = look, tap = inspect / go",
    keyDrag: "Drag",
    keyClick: "Click",
    keyWheel: "Wheel",
    hint: "Click an exhibit or a board · click the floor to walk there",
    clickToInspect: "click to inspect",
    clickToRead: "click to read",
    notebook: "Field notebook",
    exhibits: "Exhibits",
    boards: "Boards",
    studied: "studied",
    read: "read",
    tour: "Guided tour",
    continueTour: "Continue the tour",
    quiz: "Test yourself",
    bestScore: "Best score",
    close: "Close",
    prev: "Previous",
    next: "Next",
    finishTour: "Tour done: test yourself",
    tabs: { overview: "Overview", identify: "How to identify", why: "Why it matters", source: "Specimen & source" },
    life: "Mode of life",
    wall: "Test wall",
    arrangement: "Chamber arrangement",
    habitat: "Habitat",
    record: "Fossil record",
    realSize: "Real size",
    typicalSize: "Typical size",
    sizeUnknown: "typical size; this specimen's size is not given",
    sizeRuler: "Size comparison",
    terms: "Terms on this card",
    lookFor: "What to look for under the microscope",
    specimenInfo: "Specimen",
    modelCredit: "3D model",
    license: "License",
    modified: "Simplified for the web (fewer triangles, compressed file).",
    viewSource: "Open the original model",
    artBadge: "Artwork · not a real specimen",
    viewer: {
      mode: "View",
      solid: "Surface",
      xray: "X-ray",
      section: "Section",
      rotate: "Rotate",
      reset: "Reset",
      depth: "Section depth",
      loadingDetail: "Loading the high-resolution model…",
      dragHint: "Drag: rotate · wheel: zoom",
      noInternal: "This model holds the outer surface only; no internal structure.",
      internalHint: "This model holds the chambers inside the test too: look with X-ray or Section.",
      sectionHint: "Like a thin section: lift the front away and look into the chambers.",
    },
    quizTitle: "Test yourself",
    quizIntro: "8 questions: identify species, recall modes of life and arrangements. After each answer you will see why.",
    quizStart: "Start",
    question: "Question",
    correct: "Correct!",
    wrong: "Not quite.",
    answerWas: "Correct answer",
    seeResult: "See the result",
    result: "Result",
    retry: "Try again",
    backToLab: "Back to the lab",
    studyAgain: "Worth another look",
    resultMessages: ["A good start — walk the exhibits once more.", "Not bad! Have another look at a few exhibits.", "Very good! Almost a micropaleontologist.", "Perfect! You really know your foraminifera."],
    monitorTitle: "ForamID Identification Support System",
    monitorText:
      "The features you met in the lab (test wall, chamber arrangement…) are exactly the characters the identification tool asks about. Try a step-by-step genus identification from a real thin-section image.",
    monitorGo: "Open the identification tool",
    help: "Help",
  },
};
